# Generated by Django 5.0.2 on 2024-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_images',
            field=models.ManyToManyField(to='myapp.productimage'),
        ),
    ]
