# Generated by Django 5.0.2 on 2024-03-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product_available_from_product_available_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available_from',
            new_name='p_available_from',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available_until',
            new_name='p_available_until',
        ),
    ]
