# Generated by Django 5.0.2 on 2024-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_available_from_product_p_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_available_until',
            field=models.DateField(),
        ),
    ]
